# Generated by Django 3.2.17 on 2023-02-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
