# Generated by Django 3.2.17 on 2023-02-08 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_video_video_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='publish',
            new_name='published',
        ),
    ]
