# Generated by Django 4.1.5 on 2023-01-19 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_profile_country_profile_gender_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='like',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
