# Generated by Django 4.1.5 on 2023-01-19 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_video_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='like',
            new_name='video_like',
        ),
    ]
