# Generated by Django 4.1.5 on 2023-01-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_like_video_video_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
